TRAIN_TICKERS = ["AAPL", "SPY", "TSLA"]
TEST_TICKERS  = ["AMZN", "GOOG", "MSFT"]
ALL_TICKERS   = TRAIN_TICKERS + TEST_TICKERS

START_DATE = "2022-01-01"
END_DATE   = "2024-12-31"
DATA_DIR   = "data/raw"
GRAPH_DIR = "data/graphs"